export const CURRICULUM_DATA: Record<number, Record<string, string>> = {
    1: {
        "Matemática": "Produtos Notáveis e Fatoração de Expressões Algébricas.",
        "Física": "Cinemática - Fundamentos, Distância e Deslocamento Escalar, Velocidade Escalar Média, Aceleração Escalar Média e Classificação dos Movimentos.",
        "Química": "Leis Ponderais: Lavoisier e Proust, Modelos Atômicos, Efeitos Luminosos e Semelhanças Atômicas, Modelo Atômico Atual e Distribuição Eletrônica.",
        "Biologia": "Enzimas, Vitaminas, Ácidos Nucleicos - DNA e Replicação.",
        "Geografia": "Camadas da Atmosfera, Fatores do Clima e Elementos do Clima.",
        "História Geral": "Império Persa, Fenícios e Roma",
        "História do Brasil": "Colonização Francesa na América, Jesuítas e Governo Geral.",
        "Filosofia/Sociologia": "O Idealismo de Platão e A Política de Platão.",
        "Interpretação de Texto": "O papel da inferência Implícito x Explícito, Pressupostos e Subentendidos, Questões ENEM.",
        "Gramática": "Questões Ortográficas.",
        "Literatura": "Gêneros narrativos – Romance e Conto."
    },
    2: {
        "Matemática": "Sistema de Numeração Decimal, Potência de Dez e Notação Científica, Sistema Métrico Decimal, Equação do 1o Grau, Sistemas de Equação do 1a Grau, Equação de 2a Grau e Equações Biquadradas.",
        "Física": "Movimento Uniforme.",
        "Química": "Histórico da Tabela Periódica, Entendendo a Tabela, Propriedades Periódicas, Regra do Octeto, Ligação Iônica, Ligação Metálica, Ligação Covalente Simples, Dupla e Tripla e Diferenciando Ligação Iônica, Covalente e Metálica.",
        "Biologia": "Ácidos Nucleicos - Transcrição e RNA, Código Genético e Engenharia Genética.",
        "Geografia": "Fenômenos Atmosféricos, Tipos de Climas e Climogramas, Massas de Ar do Brasil e Climas do Brasil.",
        "História Geral": "Introdução à Idade Média e Feudalismo",
        "História do Brasil": "União Ibérica e Invasões Holandesas.",
        "Filosofia/Sociologia": "A Metafísica de Aristóteles, Ética e Política em Aristóteles e Helenística.",
        "Interpretação de Texto": "O que é linguagem, Variações Linguísticas e Questões ENEM.",
        "Gramática": "Processos de Formação das Palavras e Resolução de Questões.",
        "Literatura": "Gêneros narrativos – Crônica, Novela, Fábula, Conto de Fadas."
    },
    3: {
        "Matemática": "Critérios de Divisibilidade, Números Primos, Fatoração e Divisores de um Número.",
        "Física": "Movimento Uniformemente Variado.",
        "Química": "Ligação Dativa, Fórmulas Estruturais e Ressonância, Exceções ao Octeto, Geometria Molecular, Hibridação e Polaridade das Moléculas.",
        "Biologia": "Teste de DNA e Projeto Genoma Humano, Introdução à Citologia e Membrana Plasmática - Estrutura e Função.",
        "Geografia": "Estrutura Interna da Terra, Eras Geológicas e Agentes Endógenos.",
        "História Geral": "Sacro Império Romano-Germânico e Império Bizantino",
        "História do Brasil": "Tratado de Methuen, Sociedade Mineradora e Período Pombalino.",
        "Filosofia/Sociologia": "Helenística, Neoplatonismo e Neoplatonismo - Plotino.",
        "Interpretação de Texto": "Linguagem verbal x Linguagem não verbal, Capacidades/habilidades corporais humanas.",
        "Gramática": "Morfossintaxe e Substantivo.",
        "Literatura": "Elementos da narrativa."
    },
    4: {
        "Matemática": "Múltiplos e Mínimo Múltiplo Comum e Máximo Divisor Comum.",
        "Física": "Grandezas Físicas e Introdução aos Vetores, Soma Vetorial, Subtração Vetorial, Decomposição de Vetores.",
        "Química": "Forças Intermoleculares, Cálculo de Nox e Oxidação e Redução.",
        "Biologia": "Citoplasma, Fermentação e Respiração Aeróbica.",
        "Geografia": "Agentes Exógenos, Ciclo das Rochas, Geologia do Brasil e Relevo do Brasil.",
        "História Geral": "Islamismo e Reinos Africanos",
        "História do Brasil": "Revoltas Nativistas e Revoltas Separatistas.",
        "Filosofia/Sociologia": "Filosofia Medieval - Introdução e Agostinho.",
        "Interpretação de Texto": "Reconhecer as manifestações corporais de movimento, Reconhecer a necessidade de transformação de hábitos corporais.",
        "Gramática": "Plural dos substantivos compostos, Adjetivo + plural dos adjetivos compostos, Artigo e numeral.",
        "Literatura": "Conceito de Escola Literária."
    },
    5: {
        "Matemática": "Razão e Proporção.",
        "Física": "Movimentos Verticais, Velocidade Vetorial Média, Aceleração Vetorial.",
        "Química": "Balanceamento de Equações, Introdução à Química Inorgânica, Teoria de Arrhenius e Bronsted lowry para Ácidos e Bases e Teoria de Lewis para Ácidos e Bases.",
        "Biologia": "Fotossíntese e Fatores que Influenciam a Fotossíntese, Fotossíntese Bacteriana e Quimiossíntese, Núcleo Celular.",
        "Geografia": "Características Gerais e o Consumo da Água, Ciclo da Água, Rios, Águas Oceânicas e Hidrografia do Brasil.",
        "História Geral": "As Cruzadas, Crise do século XIV",
        "História do Brasil": "Período Joanino.",
        "Filosofia/Sociologia": "Tomás de Aquino e Questão dos Universais.",
        "Interpretação de Texto": "Reconhecer a linguagem corporal como meio de interação social, Linguagem mista: charge e cartum, Arte sequencial: tirinhas jornalísticas.",
        "Gramática": "Pronomes Pessoais.",
        "Literatura": "Quinhentismo."
    },
    6: {
        "Matemática": "Regra de Três Simples e Composta e Escalas Numéricas.",
        "Física": "Movimento Circular e Uniforme, Lançamento Horizontal e Lançamento Oblíquo.",
        "Química": "Estudo dos Ácidos, Nomenclatura, Estrutura e Ácidos Mais Importantes, Estudo das Bases, Nomenclatura das Bases, Bases mais Importantes, Estudo dos Sais e Nomenclatura dos Sais.",
        "Biologia": "Cariótipo, Células-Tronco e Clonagem, Ciclo Celular e Câncer.",
        "Geografia": "Biomas, Biomas e Vegetação do Brasil e Domínios Morfoclimáticos.",
        "História Geral": "Guerra dos Cem Anos e Declínio Feudal",
        "História do Brasil": "Regência de D. Pedro e Independência.",
        "Filosofia/Sociologia": "Renascimento, Maquiavel e Jean Bodin.",
        "Interpretação de Texto": "Tipos Textuais, Gêneros Textuais, Tipologia Textual Narrativa: Elementos e Estrutura.",
        "Gramática": "Pronomes indefinidos, pronomes interrogativos e pronomes possessivos, Pronomes relativos.",
        "Literatura": "Barroco."
    },
    7: {
        "Matemática": "Porcentagem.",
        "Física": "Leis de Newton, Força Peso, Força Normal, Força de Tração, Roldanas.",
        "Química": "Substâncias Inorgânicas de Destaque, Estudo dos Óxidos, Reações de Síntese, Decomposição, Reações de Simples Troca e Reações de Dupla Troca.",
        "Biologia": "Mitose, Meiose, Gametogênese e Sistemas Reprodutores Humanos.",
        "Geografia": "Domínios Morfoclimáticos, Meio Ambiente - Histórico e Conferências, Ilhas de Calor e Inundações e Inversão Térmica, Chuva Ácida, Aquecimento Global e a Questão do Lixo.",
        "História Geral": "Formação dos Estados Nacionais Modernos",
        "História do Brasil": "Primeiro Reinado.",
        "Filosofia/Sociologia": "Jacques Bossuet, Michel de Montaigne e Francis Bacon.",
        "Interpretação de Texto": "Gêneros Narrativos Literários e Gêneros Narrativos Pedagógicos.",
        "Gramática": "Pronomes relativos, Pronomes demonstrativos.",
        "Literatura": "Arcadismo."
    },
    8: {
        "Matemática": "Juros Simples e Compostos.",
        "Física": "Força Elástica, Associação de Molas, Sistemas de Blocos.",
        "Química": "Grandezas Químicas, Cálculo de Fórmulas e Cálculo Estequiométrico.",
        "Biologia": "Ciclos Ovarianos e Métodos Anticoncepcionais, Fecundação, Introdução à Embriologia, Embriologia do Anfioxo, Anexos Embrionários e Embriologia Humana.",
        "Geografia": "Desmatamento e Queimadas, Poluição da Água, Desertificação e Arenização, Crescimento Vegetativo e a Transição Demográfica e Teorias Demográficas.",
        "História Geral": "Guerra das Duas Rosas e Absolutismo",
        "História do Brasil": "Período Regencial e Revoltas Regenciais.",
        "Filosofia/Sociologia": "Thomas Hobbes, René Descartes e Meditações Metafísicas.",
        "Interpretação de Texto": "Tipologia do Discurso Narrativo e Gêneros Textuais Argumentativos.",
        "Gramática": "Pronomes demonstrativos, Questões ENEM.",
        "Literatura": "Romantismo – Introdução e contexto histórico e Poesia."
    },
    9: {
        "Matemática": "Conjuntos, Conjuntos Numéricos, Representação Decimal e Intervalos Reais.",
        "Física": "Força de Atrito, Plano Inclinado e Força Centrípeta.",
        "Química": "Rendimento menor que 100%, Excesso e Limitante, Reações Sucessivas, Pureza de Reagentes.",
        "Biologia": "Tecido Epitelial, Pele e Tecidos Conjuntivos.",
        "Geografia": "População Absoluta e População Relativa, Estrutura e Pirâmide Etária, PEA (População Economicamente Ativa) e o Mercado de Trabalho, IDH e Indicadores Sociais.",
        "História Geral": "Mercantilismo e Renascimento",
        "História do Brasil": "Segundo Reinado.",
        "Filosofia/Sociologia": "Blaise Pascal e John Locke.",
        "Interpretação de Texto": "Denotação x Conotação, Crônica.",
        "Gramática": "Verbos.",
        "Literatura": "Romantismo – Folhetim, José de Alencar e demais romancistas."
    },
    10: {
        "Matemática": "Progressão Aritmética.",
        "Física": "Trabalho mecânico, Energia cinética, Energia potencial, Energia mecânica, Potência mecânica.",
        "Química": "Estudo das Dispersões e Colóides, Separação de Colóides, Classificação das Soluções e Gráficos de Solubilidade e Solubilidade de Gases.",
        "Biologia": "Tecido Sanguíneo, Sistema Imune, Tecidos Cartilaginoso e Ósseo.",
        "Geografia": "Brasil - Crescimento Vegetativo, Brasil - Estrutura e Pirâmide Etária, Brasil - PEA e o Mercado de Trabalho, Composição da População Brasileira e Migrações - Conceitos.",
        "História Geral": "Reformas Religiosas",
        "História do Brasil": "Proclamação da República e Marechal Deodoro da Fonseca.",
        "Filosofia/Sociologia": "Espinosa e Leibniz.",
        "Interpretação de Texto": "Questões ENEM - Crônica, Gêneros Textuais, Narrativas Literárias e Conto.",
        "Gramática": "Verbos.",
        "Literatura": "Realismo – Introdução e contexto histórico e Machado de Assis."
    },
    11: {
        "Matemática": "Progressão Geométrica.",
        "Física": "Quantidade de movimento, Impulso, Sistemas Isolados, Colisões, Leis de Kepler, Lei da Gravitação Universal.",
        "Química": "Unidades de Concentração, Densidade, Diluição de Soluções, Mais Sobre Diluição, Mistura de Soluções sem Reação e Titulação.",
        "Biologia": "Tecido Muscular, Tecido Nervoso e Sistema Nervoso.",
        "Geografia": "Migrações Internacionais, Brasil - Migrações Internas, Brasil - Migrações Externas - Imigração.",
        "História Geral": "Revoluções Inglesas",
        "História do Brasil": "Marechal Floriano Peixoto.",
        "Filosofia/Sociologia": "George Berkeley, David Hume e Racionalismo e Empirismo.",
        "Interpretação de Texto": "Pleonasmo-Anáfora-Aliteração, Polissíndeto-Clímax-Quiasmo, Elipse-Zeugma-Hipérbato-Anástrofe.",
        "Gramática": "Vozes Verbais, Questões ENEM, Advérbio.",
        "Literatura": "Realismo – Naturalismo e Parnasianismo."
    },
    12: {
        "Matemática": "Semelhança de Triângulos, Relações Métricas no Triângulo Retângulo, Razões Trigonométricas no Triângulo Retângulo e Teorema de Tales.",
        "Física": "Centro de gravidade e centro de massa, Tipos de equilíbrio, Equilíbrio de um ponto material.",
        "Química": "Classificação das Reações, Estequiometria x Termoquímica, Entalpia de Combustão, Entalpia de Formação, Energia de Ligação, Lei de Hess e Entropia e Energia Livre de Gibbs.",
        "Biologia": "Sistema Sensorial, Sistema Endócrino e Sistema Respiratório.",
        "Geografia": "Urbanização - Histórico, Urbanização - Conceitos, Urbanização do Brasil e Hierarquia e Rede Urbana - Brasil.",
        "História Geral": "Iluminismo e Liberalismo",
        "História do Brasil": "Prudente de Morais, Revoltas Republicanas e Campos Sales.",
        "Filosofia/Sociologia": "Kant, Revolução Científica e Iluminismo.",
        "Interpretação de Texto": "Antítese-Paradoxo-Oxímoro, Metáfora-Símile-Alegoria.",
        "Gramática": "Preposição, Conjunções – Introdução.",
        "Literatura": "Simbolismo."
    },
    13: {
        "Matemática": "Polígonos Regulares, Circunferência e Círculo, Triângulos e Triângulo Equilátero.",
        "Física": "Tipos de alavanca, Momento de uma força, Momento binário, Equilíbrio de um corpo extenso.",
        "Química": "Velocidade das Reações, Estudo dos Gráficos de Velocidade, Como Ocorrem as Reações, Fatores que Modificam a Velocidade das Reações e Determinação da Lei da Velocidade das Reações.",
        "Biologia": "Sistema Respiratório e Sistema Circulatório.",
        "Geografia": "A questão da Moradia no Brasil, Problemas Urbanos - Brasil e Histórico e Conceitos, Agricultura - Conceitos e Brasil - Estrutura Fundiária.",
        "História Geral": "Despotismo Esclarecido",
        "História do Brasil": "Rodrigues Alves e Afonso Pena.",
        "Filosofia/Sociologia": "Voltaire, Rousseau, Montesquieu e Contratualismo.",
        "Interpretação de Texto": "Apóstrofe-Onomatopeia-Personificação-Sinestesia, Assíndeto-Anacoluto-Silepse.",
        "Gramática": "Conjunções coordenativas, Conjunções subordinativas, Questões ENEM.",
        "Literatura": "Pré-Modernismo."
    },
    14: {
        "Matemática": "Quadriláteros, Áreas do Segmento e da Coroa Circulares, Hexágono Regular e Área de Figuras Semelhantes.",
        "Física": "Massa específica e densidade, Pressão, Pressão atmosférica, Pressão nos líquidos, Teorema de Stevin, Princípio de Pascal, Empuxo - Princípio de Arquimedes, Vazão e equação da continuidade, Equação de Bernoulli.",
        "Química": "Equilíbrio Químico - Kc e Kp, Cálculo de Kc, Kp e Grau de Equilíbrio e Deslocamento de Equilíbrio.",
        "Biologia": "Sistema Digestório, Sistema Excretório e Drogas.",
        "Geografia": "Produção Agrícola no Brasil, Produção Pecuária no Brasil, Extrativismo Vegetal e Animal - Brasil, Extrativismo Mineral - Brasil e Matriz Energética - Geral e Brasil.",
        "História Geral": "Colonização da América Espanhola",
        "História do Brasil": "Nilo Peçanha e Marechal Hermes da Fonseca.",
        "Filosofia/Sociologia": "Hegel, Karl Marx e Schopenhauer.",
        "Interpretação de Texto": "Metonímia-Antonomásia-Catacrese, Ironia-Eufemismo-Hipérbole.",
        "Gramática": "Colocação pronominal.",
        "Literatura": "Vanguardas Europeias."
    },
    15: {
        "Matemática": "Poliedros Regulares, Prismas, Paralelepípedo e Cubo e Cilindro.",
        "Física": "Termologia - Fundamentos, Escalas Termométricas e Dilatação.",
        "Química": "Equilíbrio Iônico, Efeito do Íon Comum e Cálculo de pH e pOH.",
        "Biologia": "Introdução à Genética, Genealogias e Probabilidades e Erros Inatos do Metabolismo e Genes Letais.",
        "Geografia": "Petróleo e Gás Natural - Geral, Carvão Mineral - Brasil e Geral, Energia Nuclear - Geral e Brasil, Energia Hidrelétrica - Geral e Brasil e Outras Fontes de Energia Renováveis.",
        "História Geral": "Colonização da América Inglesa",
        "História do Brasil": "Veceslau Brás, Delfim Moreira e Epitácio Pessoa.",
        "Filosofia/Sociologia": "Kierkegaard, Auguste Comte, Utilitarismo, John Stuart Mill e Spencer e o Evolucionismo.",
        "Interpretação de Texto": "Questões ENEM sobre figuras de linguagem.",
        "Gramática": "Transitividade verbal, Sintaxe de regência.",
        "Literatura": "Semana de Arte Moderna, Oswald de Andrade e Tarsila do Amaral, Mário de Andrade e Manuel Bandeira."
    },
    16: {
        "Matemática": "Pirâmide, Cone, Sólidos Semelhantes e Troncos e Esfera.",
        "Física": "Calor, Princípio Geral das Trocas de Calor, Potência e Transferência de Calor.",
        "Química": "pH x Temperatura, Hidrólise e Noções de Tampão e Kps.",
        "Biologia": "Polialelismo e Sistema ABO, Sistema Rh, Segunda Lei de Mendel e Linkage.",
        "Geografia": "Introdução e Tipos de Indústria, Revoluções Industriais, Modos de Produção Industrial e Industrialização do Brasil.",
        "História Geral": "Revolução Industrial",
        "História do Brasil": "Arthur Bernardes, Washington Luís, Coluna Prestes e Cangaço.",
        "Filosofia/Sociologia": "Pragmatismo e Nietzsche.",
        "Interpretação de Texto": "Texto Poético.",
        "Gramática": "Regência verbal.",
        "Literatura": "Manuel Bandeira, Carlos Drummond de Andrade."
    },
    17: {
        "Matemática": "Estatística - Conceitos Iniciais, Organização e Representação de Dados e Representação Gráfica de Dados Estatísticos.",
        "Física": "Gases, Transformações Gasosas, Teoria Cinética dos Gases, Energia Interna, Trabalho Termodinâmico, Primeira Lei da Termodinâmica, Transformações Cíclicas, Segunda Lei da Termodinâmica e Ciclo de Carnot e Ciclo de Otto.",
        "Química": "Revisão de Oxi-redução, Pilhas, Associação de Pilha e Tirando as Dúvidas Sobre ddp.",
        "Biologia": "Genética do Sexo, Pleiotropia, Interação Gênica e Herança Quantitativa e Origem da Vida.",
        "Geografia": "Transportes, Capitalismo Comercial e Industrial, Capitalismo Financeiro e Informacional e Divisão Internacional do Trabalho (DIT).",
        "História Geral": "Independência dos EUA e Guerra Civil Americana",
        "História do Brasil": "Revolução de 1930 e Era Vargas: Governo Provisório.",
        "Filosofia/Sociologia": "Edmund Husserl, Martin Heidegger, Merleau-Ponty, Jean-Paul Sartre.",
        "Interpretação de Texto": "Intertextualidade x Interdiscursividade, Tipos de Intertextualidade I.",
        "Gramática": "Crase.",
        "Literatura": "Carlos Drummond de Andrade, Vinicius de Moraes."
    },
    18: {
        "Matemática": "Medidas de Tendência Central, Medidas de Dispersão, Estatística - Desvio Médio e Interpretação de Gráficos.",
        "Física": "Ondulatória - Fundamentos, Reflexão, Refração, Difração, Interferência, Polarização, Ressonância, Som - Propriedades Fisiológicas, Nível Sonoro e Fenômenos Sonoros.",
        "Química": "Corrosão e Proteções, Eletrólise Ígnea, Eletrólise em Solução Aquosa, Cálculos na Eletrólise e Eletrólise com Eletrodos Reativos, Eletrólise em Série.",
        "Biologia": "Origem da Vida, Conceito e Evidências da Evolução e Teorias Evolutivas.",
        "Geografia": "Velha Ordem Mundial, Nova Ordem Mundial, ONU e Desenvolvimento e Subdesenvolvimento.",
        "História Geral": "Independência da América Espanhola",
        "História do Brasil": "Era Vargas: Governo Constitucional.",
        "Filosofia/Sociologia": "Existencialismo, Hannah Arendt, Wittgenstein e Escola de Frankfurt.",
        "Interpretação de Texto": "Tipos de Intertextualidade II, Questões ENEM.",
        "Gramática": "Sujeito, Predicado.",
        "Literatura": "Cecília Meireles, Mario Quintana."
    },
    19: {
        "Matemática": "Princípio Fundamental da Contagem (PFC) e Fatorial.",
        "Física": "Efeito Doppler, Equação de Taylor e Ondas estacionárias, Cordas Sonoras, Tubo de Kundt, Tubos Sonoros Abertos, Tubos Sonoros Fechados, MHS - Fundamentos, Dinâmica do MHS e Cinemática do MHS.",
        "Química": "Introdução às Propriedades Coligativas, Ebuliometria e Criometria, Osmometria e Análise Quantitativa e Fator de Van't Hoff.",
        "Biologia": "Fatores Evolutivos, Genética das Populações e Especiação.",
        "Geografia": "Organizações Internacionais, Globalização e Comércio Internacional.",
        "História Geral": "Revolução Francesa",
        "História do Brasil": "Era Vargas: Estado Novo.",
        "Filosofia/Sociologia": "Adorno e Horkheimer, Herbert Marcuse e Walter Benjamin.",
        "Interpretação de Texto": "Coesão Textual.",
        "Gramática": "Complementos Verbais.",
        "Literatura": "Jorge Amado."
    },
    20: {
        "Matemática": "Arranjo, Permutação, Combinação, Soluções Inteiras e Não Negativas Equação Linear e Combinação com Repetição.",
        "Física": "Óptica - Fundamentos, Espelhos Planos e Espelhos Esféricos.",
        "Química": "Histórico da Química Orgânica, Classificação dos Carbonos e Hibridação, Representação das Cadeias Carbônicas e Fórmulas Moleculares, Tipo de Ligação e Cálculo de Nox, Classificação das Cadeias, Aprofundamento da Regra de Huckel, Introdução às Funções Orgânicas e Séries Orgânicas.",
        "Biologia": "Evolução Humana, Taxionomia e Introdução à Parasitologia.",
        "Geografia": "Comércio Externo - Brasil, Blocos Econômicos e Brasil - Divisão Regional.",
        "História Geral": "Era Napoleônica",
        "História do Brasil": "República Populista: Eurico Gaspar Dutra.",
        "Filosofia/Sociologia": "Jürgen Habermas e Michel Foucault.",
        "Interpretação de Texto": "Hipertexto e Linguagem Digital, Trabalhando os gêneros textuais digitais.",
        "Gramática": "Agente da passiva e predicativos, Complemento nominal.",
        "Literatura": "Graciliano Ramos."
    },
    21: {
        "Matemática": "Probabilidade - Conceitos Introdutórios, Probabilidade - Definição e Probabilidade da União de Dois Eventos.",
        "Física": "Refração, Reflexão Total, Dioptro Plano, Dispersão da Luz e Prismas.",
        "Química": "Alcanos, Alcenos, Alcadienos, Alcinos, Ciclanos e Ciclenos e Compostos Aromáticos.",
        "Biologia": "Vírus, Doenças Causadas por Ribovírus e Doenças Causadas por Desoxivírus e Retrovírus.",
        "Geografia": "Brasil - Divisão Regional, Divisão da América e Aspectos Físicos, Estados Unidos, Canadá, México e América Central.",
        "História Geral": "Primavera dos Povos",
        "História do Brasil": "República Populista: Getúlio Vargas.",
        "Filosofia/Sociologia": "Círculo de Viena, Gaston Bachelard e Karl Popper.",
        "Interpretação de Texto": "Arte e suas funções, Interpretação das artes plásticas.",
        "Gramática": "Adjunto adnominal, Adjunto adverbial e vocativo, Aposto.",
        "Literatura": "Erico Verissimo, Rachel de Queiroz e José L. do Rego."
    },
    22: {
        "Matemática": "Probabilidade Condicional e Probabilidade de Eventos Simultâneos.",
        "Física": "Lentes esféricas e Física da Visão.",
        "Química": "Álcoois, Enóis e Fenóis, Cetonas e Aldeídos, Ácidos Carboxílicos e Sais de Ácidos Carboxílicos, Éster e Anidrido e Éter.",
        "Biologia": "Bactérias, Doenças Bacterianas e Protozoários e Doenças Protozoóticas.",
        "Geografia": "América Central, América do Sul e Europa - Aspectos Físicos.",
        "História Geral": "Unificação Italiana e Unificação Alemã",
        "História do Brasil": "República Populista: Juscelino Kubitschek.",
        "Filosofia/Sociologia": "Thomas Kuhn e John Rawls.",
        "Interpretação de Texto": "\"Lendo\" uma obra de arte no ENEM, Arte pré-história: artes rupestres e megálitos.",
        "Gramática": "Concordância nominal.",
        "Literatura": "Clarisse Lispector."
    },
    23: {
        "Matemática": "Função Afim - Definição e Gráfico, Taxa de Variação da Função Afim e Coeficientes e Zero da Função Afim.",
        "Física": "Carga Elétrica, Processos de Eletrização, Lei de Coulomb, Lei de Coulomb - Casos Especiais e Campo Elétrico.",
        "Química": "Aminas, Amidas, Nitrocomposto, Nitrila e Sal Quaternário de Amônio, Haletos Orgânicos e Funções Mistas.",
        "Biologia": "Introdução à Botânica, Introdução à Reprodução Vegetal, Gimnospermas e Angiospermas, Sementes, Frutos e Reprodução Assexuada em Plantas.",
        "Geografia": "Europa.",
        "História Geral": "Imperialismo",
        "História do Brasil": "República Populista: Jânio Quadros.",
        "Filosofia/Sociologia": "Introdução à Sociologia, Auguste Comte, Émile Durkheim, Anomia em Émile Durkheim.",
        "Interpretação de Texto": "Arte na antiguidade: Egito, Grécia e Roma, Arte na América Pré-Colombiana: astecas, incas e maias.",
        "Gramática": "Concordância verbal.",
        "Literatura": "Guimarães Rosa e João Cabral de Melo Neto."
    },
    24: {
        "Matemática": "Função Linear e Funções Definidas por Várias Sentenças.",
        "Física": "Potencial Elétrico e Diferença de Potencial.",
        "Química": "Polaridade, Efeito Indutivo e Efeito Mesomérico, Solubilidade, Pontos de Fusão e de Ebulição, Acidez e Basicidade em Compostos Orgânicos e Sabão e Detergente.",
        "Biologia": "Histologia Vegetal, Raiz, Nutrição, Absorção e Condução Vegetal, Transpiração e Plantas C3, C4 e MAC.",
        "Geografia": "Europa, URSS - CEI - Histórico e Rússia e a CEI.",
        "História Geral": "Revolução Meiji",
        "História do Brasil": "República Populista: João Goulart.",
        "Filosofia/Sociologia": "Karl Marx, Max Weber, Poder e Dominação em Max Weber.",
        "Interpretação de Texto": "Arte medieval: bizantina, românica e gótica, Arte renascentista: antropocentrismo, paganismo e racionalidade.",
        "Gramática": "Período composto por coordenadas, Período composto por subordinação: adverbiais.",
        "Literatura": "Contemporaneidade – introdução e contexto histórico, Concretismo e Tropicália."
    },
    25: {
        "Matemática": "Função Quadrática, Gráfico da Função Quadrática, Zeros de uma Função Quadrática e Máximo e Mínimo da Função Quadrática.",
        "Física": "Energia Potencial Elétrica, Trabalho da Força Elétrica, Equilíbrio Eletrostático, Rigidez Dielétrica, Condutor Eletrizado e Capacitores.",
        "Química": "Isomeria Constitucional ou Plana, Isomeria Geométrica e Isomeria Óptica.",
        "Biologia": "Movimentos Vegetais e Fitormônios, Introdução à Zoologia e Filo Platyhelminthes.",
        "Geografia": "África.",
        "História Geral": "Primeira Guerra Mundial",
        "História do Brasil": "Ditadura Militar: Humberto Castelo Branco",
        "Filosofia/Sociologia": "Gilberto Freyre e Sérgio Buarque de Holanda.",
        "Interpretação de Texto": "Arte barroca, rococó e neoclássica no Brasil colonial, Arte no séc. XIX parte 01.",
        "Gramática": "Período composto por subordinação: adverbiais, Período composto por subordinação: adjetivas.",
        "Literatura": "Poesia marginal dos anos 70, poesia práxis e poesia social."
    },
    26: {
        "Matemática": "A Circunferência Trigonométrica, Razões Trigonométricas na Circunferência, Relação Fundamental da Trigonometria, Outras Razões Trigonométricas, Triângulos Quaisquer, Arcos Côngruos, Função Seno, Função Cosseno e Função Tangente.",
        "Física": "Corrente Elétrica, Tensão Elétrica e Resistência Elétrica, Leis de Ohm, Consumo de Energia Elétrica e Potência Elétrica.",
        "Química": "Transformações Gasosas, Equação de Clapeyron e Densidade, Lei de Graham, Histórico da Radioatividade, Radiações e Equações Nucleares, Meia Vida e Datação em C-14, Fissão e Fusão Nuclear e Aplicações da Radioatividade.",
        "Biologia": "Filo Nematoda, Filo Arthropoda, Filo Chordata.",
        "Geografia": "China.",
        "História Geral": "Período Entre Guerras",
        "História do Brasil": "Ditadura Militar: Artur da Costa e Silva",
        "Filosofia/Sociologia": "Florestan Fernandes e Darcy Ribeiro.",
        "Interpretação de Texto": "Arte no séc. XIX parte 02, Arte de vanguarda no início do séc. XX.",
        "Gramática": "Período composto por subordinação: substantivas, Questões ENEM.",
        "Literatura": "Lygia Fagundes Telles e Caio Fernando Abreu, Rubem Fonseca e Dalton Trevisan."
    },
    27: {
        "Matemática": "Função Exponencial - Definição, Gráfico da Função Exponencial e Equação Exponencial.",
        "Física": "Associação de Resistores e Curto-Circuito.",
        "Química": "Chuva Ácida, Camada de Ozônio, Combustíveis Fósseis, Efeito Estufa, Estrutura, Propriedades e Dilatação Anômala, Distribuição, Dessalinização, Usos e Poluição, Tipos de Água e Tratamento e Tratamento do Esgoto.",
        "Biologia": "Filo Chordata, Introdução à Ecologia, Fluxo de Energia e Ciclos Biogeoquímicos.",
        "Geografia": "Japão, Sul da Ásia – Aspectos Físicos e Humanos e Econômicos, Índia e Oriente Médio – Aspectos Físicos.",
        "História Geral": "Revolução Russa, Nazismo, Fascismo, Segunda Guerra Mundial, Descolonização da África, Revolução Chinesa e Guerra Fria",
        "História do Brasil": "Ditadura Militar: Emílio Garrastazu Médici.",
        "Filosofia/Sociologia": "Desigualdades Sociais, Violência, Racismo, Machismo e Patriarcalismo, Pierre Bourdieu.",
        "Interpretação de Texto": "Arte moderna e pós-moderna, Expressões estéticas contemporâneas.",
        "Gramática": "Vírgula.",
        "Literatura": "Manifestações literárias no século XXI – Prosa e Poesia."
    },
    28: {
        "Matemática": "Logaritmos - Definição, Propriedades Operatórias dos Logaritmos, Mudança de Base, Equações Logarítmicas e Função Logarítmica.",
        "Física": "Amperímetro e Voltímetro, Ponte de Wheatstone e Geradores.",
        "Química": "Cisão da Ligações e Classificação das Reações, Moderna Abordagem das Reações Orgânicas, Reações Ácido-Base e Esterificação, Hidrolise Ácida e Alcalina (Saponificação) de Éster e Transesterificação (Biodiesel) e Reações de Oxidação.",
        "Biologia": "Ciclos Biogeoquímicos, Dinâmica das Populações e Relações Ecológicas.",
        "Geografia": "Oriente Médio.",
        "História Geral": "Guerra Fria",
        "História do Brasil": "Ditadura Militar: Ernesto Geisel, Ditadura Militar: João Batista Figueiredo, Nova República: José Sarney, Nova República: Constituição de 1988 e Nova República: Fernando Collor de Mello.",
        "Filosofia/Sociologia": "Sociologia da Educação, Movimentos Sociais e Feminismo.",
        "Interpretação de Texto": "Questões ENEM sobre arte.",
        "Gramática": "Vírgula.",
        "Literatura": "Trovadorismo e Humanismo."
    },
    29: {
        "Matemática": "Distância Entre Dois Pontos, Áreas e Alinhamento de Pontos, Equação Geral da Reta, Equação Reduzida da Reta, Equação Reduzida da Circunferência e Equação Geral da Circunferência.",
        "Física": "Eletromagnetismo - Fundamentos, Receptores, Circuito com Gerador Receptor e Resistor, Soma das Tensões em um Circuito, Leis de Kirchhoff, Fontes de Campo Magnético e Força Magnética.",
        "Química": "Adição em Alcenos e Ciclenos, Adição em Alcinos e Alcadienos, Desidratação de Álcoois e Substituição em Alcanos e Aromáticos.",
        "Biologia": "Sucessão Ecológica e Biosfera.",
        "Geografia": "Oriente Médio, Conflito Israel, Ásia e Regiões Polares - Ártico e Antártica.",
        "História Geral": "Revolução Islâmica",
        "História do Brasil": "Nova República: Itamar Franco e Nova República: Fernando Henrique Cardoso.",
        "Filosofia/Sociologia": "Reforma Agrária, Sociologia do Trabalho e Declaração dos Direitos Humanos.",
        "Interpretação de Texto": "Fotografia e Cinema, Dança como expressão corporal e identitária.",
        "Gramática": "Outros sinais de pontuação.",
        "Literatura": "Classicismo."
    },
    30: {
        "Matemática": "Introdução às Matrizes, Operações com Matrizes e Multiplicação de Matrizes.",
        "Física": "Força Magnética, Indução Eletromagnética, Transformadores, Teoria da Relatividade, Física Quântica e Efeito Fotoelétrico e Análise Dimensional.",
        "Química": "Reações com Aldeídos e Cetonas e Polímeros.",
        "Biologia": "Desequilíbrios Ecológicos e Poluição.",
        "Geografia": "Conflitos Internacionais.",
        "História Geral": "Ditaduras da América Latina",
        "História do Brasil": "Nova República: Luiz Inácio Lula da Silva.",
        "Filosofia/Sociologia": "Constituição Cidadã de 1988, Cultura e Patrimônio, Antropologia – Métodos e Fundamentos.",
        "Interpretação de Texto": "Música no ENEM, Breve história da música no Brasil, Questões ENEM sobre música.",
        "Gramática": "Outros sinais de pontuação, Questões ENEM.",
        "Literatura": "Eça de Queiroz, Fernando Pessoa e José Saramago."
    }
};

// Helper to get curriculum
export const getCurriculumForWeek = (week: number) => {
    return CURRICULUM_DATA[week] || null;
};
