import { NextResponse } from 'next/server';
import { supabase } from '@/lib/supabase';
import { GoogleGenerativeAI } from "@google/generative-ai";

export const dynamic = 'force-dynamic';

// Cache interface
interface DailyMotivation {
    id: string;
    date: string;
    message: string;
}

export async function GET() {
    try {
        // Use Brazil time to determine "today"
        const today = new Date().toLocaleDateString('en-CA', { timeZone: 'America/Sao_Paulo' });

        // 0. Check Supabase connection
        if (!supabase) {
            console.warn("Supabase client not initialized");
            // Fallback
            return NextResponse.json({ message: "A disciplina é a mãe do sucesso. Vamos!" });
        }

        // 1. Try to fetch today's message from DB (Generated by Cron)
        const { data: existing } = await supabase
            .from('daily_motivations')
            .select('message')
            .eq('date', today)
            .single();

        if (existing) {
            return NextResponse.json({ message: existing.message });
        }

        // 2. Fallback: If Cron failed or hasn't run, generate on the fly
        console.warn("No motivation found for today. Generating fallback...");

        const apiKey = process.env.GEMINI_API_KEY || process.env.NEXT_PUBLIC_GEMINI_API_KEY;
        if (!apiKey) {
            return NextResponse.json({ message: "Bora estudar! O futuro te espera. 🚀" });
        }

        const genAI = new GoogleGenerativeAI(apiKey);
        const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

        const prompt = `
            Gere UMA frase curta e motivacional para um estudante que está acessando uma plataforma de estudos (ENEM/Concursos).
            Regras:
            1. Curta (máximo 15 palavras).
            2. Direta e disciplinada (estilo "Hard Work").
            3. Sem "coachês" barato ou excesso de empolgação.
            4. Tom sério mas encorajador.
            5. NÃO use aspas na resposta.
            6. SEJA CRIATIVO e EVITE repetições de frases clichês.
        `;

        const result = await model.generateContent(prompt);
        const response = await result.response;
        let text = response.text().trim().replace(/^["']|["']$/g, '');

        // Save this fallback so we don't generate again today
        await supabase.from('daily_motivations').upsert({ date: today, message: text }, { onConflict: 'date' });

        return NextResponse.json({ message: text });

    } catch (error) {
        console.error("Error in daily motivation API:", error);
        return NextResponse.json({ message: "A disciplina é a mãe do sucesso. Vamos!" }, { status: 200 }); // Worst case
    }
}
