import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase-server';
import { GoogleGenerativeAI } from "@google/generative-ai";
import { getRandomQuote } from '@/lib/quotes';

export const dynamic = 'force-dynamic';

export async function GET() {
    try {
        // Use Brazil time to determine "today"
        const today = new Date().toLocaleDateString('en-CA', { timeZone: 'America/Sao_Paulo' });

        // 0. Init Supabase (Server Client)
        const supabase = await createClient();

        if (!supabase) {
            console.warn("Supabase client not initialized");
            // Fallback
            return NextResponse.json({ message: getRandomQuote(), seen: false });
        }

        // 0.5 Check if User has already seen today's message
        const { data: { user } } = await supabase.auth.getUser();
        if (user) {
            const { data: view } = await supabase
                .from('daily_motivation_views')
                .select('date')
                .eq('user_id', user.id)
                .eq('date', today)
                .single();

            if (view) {
                // User already saw the message today
                return NextResponse.json({ message: null, seen: true });
            }
        }

        // 1. Try to fetch today's message from DB (Generated by Cron)
        const { data: existing } = await supabase
            .from('daily_motivations')
            .select('message')
            .eq('date', today)
            .single();

        let messageToSend = "";

        if (existing) {
            messageToSend = existing.message;
        } else {
            // 2. Fallback: If Cron failed or hasn't run, generate on the fly
            console.log("No motivational message in DB. Attempting generation...");

            const apiKey = process.env.GEMINI_API_KEY || process.env.NEXT_PUBLIC_GEMINI_API_KEY;

            if (!apiKey) {
                console.warn("MISSING GEMINI_API_KEY. Using random fallback quote.");
                messageToSend = getRandomQuote();
            } else {
                try {
                    const genAI = new GoogleGenerativeAI(apiKey);
                    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

                    const prompt = `
                        Gere UMA frase curta e motivacional para um estudante que está acessando uma plataforma de estudos (ENEM/Concursos).
                        Regras:
                        1. Curta (máximo 15 palavras).
                        2. Direta e disciplinada (estilo "Hard Work").
                        3. Sem "coachês" barato ou excesso de empolgação.
                        4. Tom sério mas encorajador.
                        5. NÃO use aspas na resposta.
                        6. SEJA CRIATIVO e EVITE repetições de frases clichês.
                    `;

                    const result = await model.generateContent(prompt);
                    const response = await result.response;
                    messageToSend = response.text().trim().replace(/^["']|["']$/g, '');

                    if (!messageToSend) throw new Error("Empty response from AI");

                } catch (aiError) {
                    console.error("AI Generation Failed:", aiError);
                    messageToSend = getRandomQuote();
                }
            }

            // Save this message (whether AI or Fallback) so it persists for the day
            if (messageToSend) {
                await supabase.from('daily_motivations').upsert({ date: today, message: messageToSend }, { onConflict: 'date' });
            }
        }

        return NextResponse.json({ message: messageToSend, seen: false });

    } catch (error) {
        console.error("Critical error in daily motivation API:", error);
        return NextResponse.json({ message: getRandomQuote(), seen: false }, { status: 200 });
    }
}
